version: "3.9"

services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    image: playwright-js-tests
    container_name: playwright-tests
    working_dir: /app
    volumes:
      - .:/app
    stdin_open: true
    tty: true
