name: Packeta CI Tests

# definice "kdy" se má job spustit - zde př push do main případně pull requestu do main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# definování jobu - bude běžet na ubuntu-latest
jobs:
  test:
    name: Run Playwright + Newman tests
    runs-on: ubuntu-latest

#### KROKY #### 

# stažení aktuálního repo do prostředí
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

# nastavení prostředí na požadovanou verzi (node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

# instalování závislosti
      - name: Install dependencies
        run: npm ci

# instalace chromia (stahujeme jen to, pro účely testu, časovou náročnost a paměť)
      - name: Install Playwright browsers
        run: npx playwright install chromium

# spuštění samotného testu v Playwright
      - name: Run Playwright tests
        run: npx playwright test

# spuštění samotného testu v Newman (kolekce v Postman)
      - name: Run Newman collection (Postman)
        run: |
          npx newman run postman/packeta.json \
            --environment postman/packeta_env.json \
            --reporters cli
